// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBEmCwqwrZZWTlrQnxZEeqrUtdeg-FHw',
    appId: '1:646013770932:web:ac4ec1244eaf3e76ad0be1',
    messagingSenderId: '646013770932',
    projectId: 'flutter-track-bites',
    authDomain: 'flutter-track-bites.firebaseapp.com',
    storageBucket: 'flutter-track-bites.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM31-WPmDZkKNZXATORaTGtniBxGxWJNs',
    appId: '1:646013770932:android:97f544f3941516cbad0be1',
    messagingSenderId: '646013770932',
    projectId: 'flutter-track-bites',
    storageBucket: 'flutter-track-bites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJAwkUpapIYcnN5_ItKnL5dJC0MXppR4',
    appId: '1:646013770932:ios:c5ba00066d73e78cad0be1',
    messagingSenderId: '646013770932',
    projectId: 'flutter-track-bites',
    storageBucket: 'flutter-track-bites.appspot.com',
    iosBundleId: 'com.example.flutterTrackbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJAwkUpapIYcnN5_ItKnL5dJC0MXppR4',
    appId: '1:646013770932:ios:c5ba00066d73e78cad0be1',
    messagingSenderId: '646013770932',
    projectId: 'flutter-track-bites',
    storageBucket: 'flutter-track-bites.appspot.com',
    iosBundleId: 'com.example.flutterTrackbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUBEmCwqwrZZWTlrQnxZEeqrUtdeg-FHw',
    appId: '1:646013770932:web:451228380254b9d2ad0be1',
    messagingSenderId: '646013770932',
    projectId: 'flutter-track-bites',
    authDomain: 'flutter-track-bites.firebaseapp.com',
    storageBucket: 'flutter-track-bites.appspot.com',
  );
}
